/*
 * Resources.Designer.cs --
 *
 * Copyright (c) 2007-2012 by Joe Mistachkin.  All rights reserved.
 *
 * See the file "license.terms" for information on usage and redistribution of
 * this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: @(#) $Id: $
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8964
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eagle._Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EagleTest.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string auxiliary_eagle {
            get {
                return ResourceManager.GetString("auxiliary.eagle", resourceCulture);
            }
        }

        internal static string compat_eagle {
            get {
                return ResourceManager.GetString("compat.eagle", resourceCulture);
            }
        }

        internal static string csharp_eagle {
            get {
                return ResourceManager.GetString("csharp.eagle", resourceCulture);
            }
        }

        internal static string database_eagle {
            get {
                return ResourceManager.GetString("database.eagle", resourceCulture);
            }
        }

        internal static string embed_eagle {
            get {
                return ResourceManager.GetString("embed.eagle", resourceCulture);
            }
        }

        internal static string exec_eagle {
            get {
                return ResourceManager.GetString("exec.eagle", resourceCulture);
            }
        }

        internal static string file1_eagle {
            get {
                return ResourceManager.GetString("file1.eagle", resourceCulture);
            }
        }

        internal static string file2_eagle {
            get {
                return ResourceManager.GetString("file2.eagle", resourceCulture);
            }
        }

        internal static string file2u_eagle {
            get {
                return ResourceManager.GetString("file2u.eagle", resourceCulture);
            }
        }

        internal static string file3_eagle {
            get {
                return ResourceManager.GetString("file3.eagle", resourceCulture);
            }
        }

        internal static string info_eagle {
            get {
                return ResourceManager.GetString("info.eagle", resourceCulture);
            }
        }

        internal static string init_eagle {
            get {
                return ResourceManager.GetString("init.eagle", resourceCulture);
            }
        }

        internal static string list_eagle {
            get {
                return ResourceManager.GetString("list.eagle", resourceCulture);
            }
        }

        internal static string object_eagle {
            get {
                return ResourceManager.GetString("object.eagle", resourceCulture);
            }
        }

        internal static string pkgIndex_eagle {
            get {
                return ResourceManager.GetString("pkgIndex.eagle", resourceCulture);
            }
        }

        internal static string pkgIndex_tcl {
            get {
                return ResourceManager.GetString("pkgIndex.tcl", resourceCulture);
            }
        }

        internal static string pkgt_eagle {
            get {
                return ResourceManager.GetString("pkgt.eagle", resourceCulture);
            }
        }

        internal static string platform_eagle {
            get {
                return ResourceManager.GetString("platform.eagle", resourceCulture);
            }
        }

        internal static string process_eagle {
            get {
                return ResourceManager.GetString("process.eagle", resourceCulture);
            }
        }

        internal static string runopt_eagle {
            get {
                return ResourceManager.GetString("runopt.eagle", resourceCulture);
            }
        }

        internal static string safe_eagle {
            get {
                return ResourceManager.GetString("safe.eagle", resourceCulture);
            }
        }

        internal static string shell_eagle {
            get {
                return ResourceManager.GetString("shell.eagle", resourceCulture);
            }
        }

        internal static string shim_eagle {
            get {
                return ResourceManager.GetString("shim.eagle", resourceCulture);
            }
        }

        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }

        internal static string test_eagle {
            get {
                return ResourceManager.GetString("test.eagle", resourceCulture);
            }
        }

        internal static string testlog_eagle {
            get {
                return ResourceManager.GetString("testlog.eagle", resourceCulture);
            }
        }

        internal static string unkobj_eagle {
            get {
                return ResourceManager.GetString("unkobj.eagle", resourceCulture);
            }
        }

        internal static string unzip_eagle {
            get {
                return ResourceManager.GetString("unzip.eagle", resourceCulture);
            }
        }

        internal static string update_eagle {
            get {
                return ResourceManager.GetString("update.eagle", resourceCulture);
            }
        }

        internal static string vendor_eagle {
            get {
                return ResourceManager.GetString("vendor.eagle", resourceCulture);
            }
        }

        internal static string word_tcl {
            get {
                return ResourceManager.GetString("word.tcl", resourceCulture);
            }
        }
    }
}
